name: Deploy to Cloudflare pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Retrieve the latest mdBook release by noarchwastaken
        run: |
          wget https://github.com/noarchwastaken/mdBook/releases/download/v0.4.7-noarchwastaken/mdbook-v0.4.7-noarchwastaken-x86_64-unknown-linux-gnu.tar.gz
          tar -xvf mdbook-v0.4.7-noarchwastaken-x86_64-unknown-linux-gnu.tar.gz

      - name: Update apt cache
        run: sudo apt update -y

      - name: Install BeautifulSoup for lazyimg.py
        run: sudo apt install python3-bs4 -y

      - name: Build the book
        run: |
          ./mdbook build

      - name: Patch the output for lazy image loading
        run: python3 utils/lazyimg.py book

      - name: Push the book to the CF pages repo
        uses: cpina/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'book'
          destination-github-username: 'noarchwastaken'
          destination-repository-name: 'privacy-pages'
          user-email: notareal@email.com

  build-tw:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Retrieve the latest mdBook release by noarchwastaken
        run: |
          wget https://github.com/noarchwastaken/mdBook/releases/download/v0.4.7-noarchwastaken/mdbook-v0.4.7-noarchwastaken-x86_64-unknown-linux-gnu.tar.gz
          tar -xvf mdbook-v0.4.7-noarchwastaken-x86_64-unknown-linux-gnu.tar.gz

      - name: Update apt cache
        run: sudo apt update -y

      - name: Install BeautifulSoup for lazyimg.py
        run: sudo apt install python3-bs4 -y

      - name: Install OpenCC
        run: sudo apt install opencc -y

      - name: Patch the book for fonts and HTML language attribute
        run: git apply utils/0001-traditional.patch

      - name: Build the book
        run: |
          ./mdbook build

      - name: Patch the output for lazy image loading
        run: python3 utils/lazyimg.py book

      - name: Convert the book to Traditional Chinese
        run: sh utils/opencc.sh book

      - name: Push the book to the CF pages repo
        uses: cpina/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'book'
          destination-github-username: 'noarchwastaken'
          destination-repository-name: 'privacy-pages-tw'
          user-email: notareal@email.com
